package com.java.StocksList;

public class StocksList {

	public String[] ListofStocks = { "ACB", "VEON", "NIO", "GGB", "ABEV", "SWN", "NOK", "RRC", "ASLN", "RIG", "QD",
			"VSTM", "HEXO", "SSI", "AR", "ECA", "CPE", "OIBR/C", "OAS", "AUY", "ODP", "MUX", "QEP", "VIVE", "KGC",
			"SAN", "EPSN", "AKS", "AM", "PTI", "MNK", "ENDP", "VAL", "APHA", "PLUG", "HL", "JCP", "ADMP", "GPOR", "OGI",
			"NBR", "NOG", "HMY", "LPI", "VHC", "DNR", "BTG", "AKBA", "WTI", "WKHS", "CDEV", "TNK", "LYG", "FNMA",
			"BCRX", "GPRO", "FUV", "CIG", "PRTY", "MGI", "TOO", "EROS", "SID", "ACST", "CX", "PPDF", "IAG", "XXII",
			"AVP", "JSTTY", "TRNX", "SRCI", "WPG", "OPK", "CPG", "ORGO", "PBI", "NE", "HEPA", "RBZ", "GRPN", "BTE",
			"TXMD", "SDRL", "NBEV", "CRNT", "CHS", "NAT", "ATRS", "VRAY", "CETV", "CCO", "HIMX", "TTOO", "EXK", "TORC",
			"EXPR", "CPRX", "IMGN", "CORV", "CEI", "LXRX", "GNW", "XNET", "KDMN", "MNKD", "TRUE", "AGRX", "ASTC",
			"FMCC", "SLCA", "ACOR", "GERN", "RES", "FPRX", "BBAR", "AGEN", "FLDM", "LTS", "TLRD", "CYH", "SLDB", "ENIC",
			"YRCW", "MOBL", "XOG", "JE", "CLNY", "GER", "BCLYF", "AMRX", "GTE", "TANH", "PDLI", "FSM", "WAFU", "ALNA",
			"MTNB", "QTT", "CSLT", "EYPT", "NIHD", "CBL", "CVSI", "IPI", "AEG", "SESN", "GGN", "QBIO", "ONCY", "FOMX",
			"CNSL", "GLBS", "SUPV", "SBBP", "ANH", "ZIOP", "NEPT", "CJJD", "STCN", "EMIS", "AXU", "HBM", "BIOS", "TTSH",
			"RIOT", "GNC", "ACRX", "HYRE", "RIGL", "TNXP", "CLSD", "SCOR", "AKRX", "APDN", "SVM", "FAMI", "PRTK",
			"ITHUF", "SPCE/WS", "CELH", "VTNR", "NLS", "WIT", "CIOXY", "VVR", "AMRS", "MDGS", "CRBP", "FAX", "ORBC",
			"CALA", "GORO", "TTI", "SOGO", "OCUL", "SUNW", "MLSS", "CYCN", "SNDL", "FCSC", "CAAP", "SONM", "DPLO",
			"DRRX", "AVGR", "QUAD", "AFMD", "OVID", "EVOK", "VBLT", "KSHB", "NBRV", "BKCC", "SRNE", "RBBN", "NEX",
			"MRNS", "ZSAN", "JMEI", "INO", "UUUU", "SMLP", "ARLO", "VNTR", "MEET", "RRD", "BTTR", "CASA", "NH", "SLS",
			"FENG", "AHT", "WETF", "PIRS", "HIO", "OBSV", "HPR", "LLNW", "OCX", "KALA", "ETM", "EARS", "KIRK", "SJT",
			"ADMA", "FET", "SAEX", "FTSI", "USAS", "CEPU", "OPGN", "RMTI", "ACRS", "CASI", "NSRPF", "WPRT", "PBPB",
			"CMRX", "JNCE", "UXIN", "HRVSF", "ALTM", "NCZ", "ISEE", "CLNE", "EMX", "WATT", "EGLE", "MRKR", "SIGA",
			"AETUF", "CERS", "NVAX", "MEDIF", "REI", "ARTL", "NEXCF", "CKPT", "MBIO", "BKEP", "FLNT", "WTER", "BBCP",
			"PDS", "TRVG", "ADRO", "CDR", "PHAS", "SNCR", "CMCM", "SB", "VUZI", "AVXL", "ARTX", "YJ", "NDP", "NTGN",
			"CLMT", "UEPS", "PHUN", "GLYC", "SMSI", "TYME", "LGGNF", "MTC", "SELB", "SVNLY", "MRIN", "LMCNF", "DLNG",
			"INAP", "KZR", "RFP", "CTTMF", "TUSK", "GNLN", "AVH", "AQMS", "RLH", "EIGI", "CTSO", "KGFHY", "MBRX", "DS",
			"ASX", "RYAM", "SYBX", "PBCRF", "MCF", "ONDK", "SURF", "OESX", "WRTC", "PPR", "TIGR", "YVR", "OBNNF",
			"STXS", "LAC", "BGFV", "SD", "HIL", "ORHOF", "STG", "ZEST", "DHXM", "ARAY", "ATHX", "CPST", "AFI", "BLRX",
			"INFI", "CAAS", "DSX", "KNDI", "LAIX", "PER", "FTK", "TNP", "CIK", "MLNT", "BLNK", "CTRM", "PHCEF", "BIMI",
			"FBIO", "CDXC", "SREV", "KNTNF", "SCYX", "RMBL", "SGRP", "RESN", "OCN", "CFMS", "IFRX", "MOTS", "APTO",
			"AKTX", "ARC", "NMCI", "VREOF", "PACD", "REFR", "CEMI", "EVC", "BYDDF", "EGY", "BTGOF", "SYRS", "JILL",
			"ABEO", "GSS", "STKL", "OBLN", "PRPO", "DSE", "SPOXF", "MARA", "NURO", "LEJU", "NXE", "KODK", "TWI", "MCRB",
			"ECOR", "WNDW", "MFG", "AUG", "DSKE", "PBT", "HZN", "TCS", "WSG", "BOXL", "TH", "TTPH", "TRSSF", "PXLW",
			"PLNHF", "RVP", "LIFE", "HHT", "PVL", "XBIO", "VERI", "JT", "ESTE", "STIM", "OPTT", "FPAFY", "CRIS", "ELOX",
			"MAKSY", "LBY", "FPAY", "TPHS", "CRESY", "MRSN", "BBW", "DRTT", "CRRFY", "UMC", "MDCA", "JMLP", "GALT",
			"EYEN", "CNPOF", "SGSVF", "AT", "SKLKY", "TMQ", "SOLO", "LKCO", "GNCA", "CVIA", "CPSH", "PSTV", "ICON",
			"FLL", "MIN", "CERC", "OSG", "PIM", "LIVX", "CWBR", "VLRX", "MMLP", "APTX", "GDRZF", "SRTS", "SEAC", "ROSE",
			"SND", "VGWCF", "PXS", "PTMN", "LIQT", "RKDA", "XIN", "IRR", "IDRA", "LONE", "CLSN", "GCAP", "MRAM", "GRWG",
			"DHF", "YCBD", "NINE", "MBII", "NLTX", "TRMT", "IPWR", "TUES", "ROAN", "CDTX", "BW", "DRD", "MCC", "RAIL",
			"LMB", "ANIX", "FTNW", "SAVA", "CSU", "JP", "DWSN", "MGF", "ATOM", "OSS", "PFIE", "SLGG", "CANF", "CLXT",
			"AGTC", "ZVO", "PTE", "SOL", "GEN", "DTEA", "TSSI", "DHY", "RTIX", "USX", "NLNK", "PRTS", "NETE", "GLXZ",
			"NHYDY", "DGSE", "SRAX", "AUOTY", "PLPRF", "SFUN", "HCHC", "CCLP", "BNED", "CLDX", "SUP", "ACTG", "ATOS",
			"ATTO", "RTW", "SMTX", "ALT", "ENZ", "BDRBF", "HNHAF", "ICL", "NK", "HWCC", "PBTS", "RWLK", "MMX", "SPRT",
			"NSCO", "NM", "LXU", "EDAP", "MAPIF", "PED", "CTRC", "YUMA", "CRVS", "RVXCF", "SAUC", "LTRX", "GASS",
			"MEIP", "ALSK", "CIH", "ITRM", "HNRG", "TROV", "CETX", "AXTI", "AKBTY", "INCZY", "APEX", "NMTC", "TGA",
			"NEOS", "INWK", "UAN", "BIREF", "ELTK", "ABUS", "HBIO", "ONCS", "FRBK", "BCLI", "TPRXF", "SACH", "ARHH",
			"NSYS", "NWVCF", "ATGN", "OTLK", "EMMS", "HCFT", "SKYS", "DRAD", "IDSA", "PLIN", "STRM", "BILZF", "GEVO",
			"HNNMY", "OCANF", "RIBT", "JNBYF", "HOKCY", "CMU", "VTVT", "AHCOW", "CGA", "ICLK", "WWR", "POEFF", "DHX",
			"NWHM", "SAMOF", "XCUR", "MDNAF", "TOUR", "ATIF", "BWEN", "SCPH", "MBNKF", "NGENF", "OTIC", "FEDU", "BHAT",
			"AQB", "OHAI", "STKS", "REXN", "VERU", "VHI", "FNJN", "SLNO", "JG", "RHE", "ORMP", "OROCF", "CWXZF", "GIGM",
			"SUTNY", "SPEX", "GTYH", "PETZ", "MGDPF", "GFASY", "IRIX", "CLRB", "THTX", "REKR", "MN", "FFHL", "QTRH",
			"MDCL", "SSKN", "AESE", "STON", "LEE", "URPTF", "HEBT", "METC", "BBX", "PSV", "PANL", "EPIX", "CLPS",
			"KRMD", "BASI", "YGYI", "MNDO", "NUPMF", "ELVT", "SORL", "HAPP", "ELGX", "BLIN", "VOC", "PTOTF", "PIRGF",
			"MOGU", "GBR", "WORX", "ALPN", "NNVC", "MJWNF", "SCPE/WS", "SINT", "IRVRF", "EXFO", "PSTI", "UEEC", "IEA",
			"DXYN", "MYSZ", "TMMFF", "AGFS", "MBOT", "YTRA", "MNLO", "DXLG", "ALIM", "LSYN", "USWS", "KKPNY", "CRHM",
			"VOXX", "POAI", "CLUB", "SMTS", "MXC", "GTIM", "KXIN", "ATDRY", "WARFY", "DOGZ", "MACK", "CNET", "XYF",
			"PEYE", "PLG", "THMO", "GRYN", "SMED", "DPMLF", "III", "VJET", "AVCO", "CNSP", "CMT", "MREO", "UDFI",
			"GENE", "ACY", "SELF", "MDWD", "BHTG", "XAUMF", "CURR", "JMP", "BONXF", "SDDXF", "CGOOF", "TSLLF", "RMNI",
			"VVUS", "NTWK", "YAYO", "TRPX", "RCAR", "PCYG", "AUTO", "RCMT", "INOD", "CXDC", "GELYF", "CIF", "DIIBF",
			"SBPH", "BSQR", "EVLLF", "BOSC", "CAPR", "GSUM", "FKWL", "CCORF", "CTHR", "VODPF", "JUSHF", "HOTH", "TPRFF",
			"GTBDF", "RAVE", "AACG", "INMB", "CHEK", "POLA", "CPYYY", "TCON", "AAVVF", "TPCS", "AMNF", "SCRYY", "ACER",
			"ZKIN", "GAPFF", "NNDIF", "NNDM", "FLWPF", "RNWK", "PFSW", "ATHE", "SYCRF", "NDVLY", "BCOM", "GV", "CSS",
			"CHRA", "COGNY", "TURN", "CO", "PUYI", "LNNGF", "BKTI", "FDCHF", "CPYYF", "MCHX", "BCDA", "BCEKF", "TKGBY",
			"MTBC", "SCHYF", "MAPGF", "ADIL", "OIIM", "EAST", "AEHR", "RMED", "UFAB", "CNRAF", "GRAM", "SHLO", "EMMA",
			"EVSI", "ETTX", "EDNT", "WLMS", "AQUI", "FORD", "NYMX", "POWW", "AIRI", "SLRX", "AWX", "SNDE", "OMEX",
			"MEGEF", "EMKR", "VRNA", "IMMP", "UCLE", "LQDA", "PEYUF", "RELV", "QUESD", "SALM", "AGE", "RSGUF", "LEAF",
			"AERO", "SMIT", "GTCH", "APWC", "HHS", "AEMD", "XELB", "CBOF", "AMTX", "SMMT", "LYSDY", "PTCHF", "VIRC",
			"WHLR", "AWRE", "RHDGF", "PDSB", "NCSM", "BNEFF", "AHC", "LYSCF", "EOFBF", "JVA", "DAIO", "NVCN", "BAFBF",
			"CORVF", "CTEK", "GNSS", "RSLSD", "KBSF", "DVD", "CCOM", "QES", "WTT", "AEY", "GVP", "OBCI", "NTZ", "WDGJF",
			"WHLM", "CIBEY", "ZMTP", "SHCAY", "KNWN", "CLWT", "QRHC", "ZTCOF", "TGCDF", "NOVN", "PRCP", "MOSY", "FSI",
			"UTSI", "LUB", "BOIVF", "GROW", "VERO", "SANW", "SPGYF", "BBGI", "TSCDF", "ECNCF", "PLAG", "MIND", "LTBR",
			"WINT", "JLMC", "OWPC", "ISNS", "JBFCF", "GLCNF", "AXLA", "SIFY", "CLOEF", "DRIO", "AAMAF", "INRLF", "KGJI",
			"SJMHF", "BVSN", "SYNC", "OSN", "BGI", "LWAY", "PME", "PDDPF", "INNV", "IVPAF", "TC", "FBASF", "ARMP",
			"VOLT", "CRTPF", "DSGT", "SZBI", "GEC", "CEL", "MDLY", "EVRC", "NFC/WS", "TENX", "IMPJY", "RBSPF", "CAOVF",
			"ARNGF", "TAIT", "LQSIF", "VREYF", "PRPH", "AP", "KRBFD", "APOP", "TWMC", "MLSPF", "OQMGF", "PRGX", "CNFR",
			"PLXP", "USIO", "DTSS", "TCCO", "MTL", "RNECY", "FRSX", "PRTH", "AAME", "GLMD", "STGPF", "VRRMW", "GUZOF",
			"GTGT", "WIMHF", "MRVGF", "BTN", "DGLY", "AUIAF", "DMAC", "INDXF", "NTIP", "HGLI", "VST/WS/A", "BBI",
			"RTOXF", "JAN", "CPIX", "MZDAY", "IMRN", "PGUUF", "RSTGF", "WFCF", "ZOOM", "FPHHF", "MAGS", "VTSI", "SOFO",
			"SPI", "TATT", "HGHAF", "KOSS", "ISSC", "IITSF", "CCHWF", "CPAMF", "IMAC", "PAYD", "AHOTF", "ADYX", "ECIFY",
			"AIRRF", "CPKPY", "ANCN", "BTBIF", "MAKSF", "CLRO", "WINR", "ISYRF", "DSEEY", "DNGDF", "HLDCY", "FVE", "NL",
			"BBAJF", "IINX", "SBMFF", "SHPMF", "CPAH", "ALIAF", "MRIC", "KGFHF", "LFSYF", "IBAL", "CRBJF", "WRTBY",
			"MCESF", "RTOBF", "HUTMF", "PBIO", "ACDSF", "FNGR", "CRLFF", "STKAF", "NAOV", "DSWL", "MDRR", "GCTAY",
			"APT", "NCRA", "WELX", "SCKT", "TNYYF", "CNF", "MKGI", "GFSZF", "AXXTF", "INVVY", "EDSA", "CLBS", "EQS",
			"FCCG", "RAND", "SCEXF", "MOXC", "BKRIY", "BDRAF", "BMRA", "POFCF", "NGCRF", "VCVOF", "HOLHF", "TRVI",
			"PBSFY", "USNZY", "ANTE", "RCRT", "MTPOF", "JSNSF", "NNCSF", "TDW/WS/A", "HZHI", "BSTG", "NES", "UONE",
			"EXCE", "LEDS", "CPWHF", "DLNDY", "SGAMY", "CREX", "HIHO", "OPHC", "ATVDY", "WDBG", "CVV", "RSSS", "TLLYF",
			"PMMTF", "ZDGE", "LAZY", "PRRFY", "SEMFF", "CVALF", "TRXD", "PLTYF", "AWLCF", "DAGXF", "PGVI", "MARPS",
			"SRTTY", "XTNT", "NHLD", "GMDA", "CHPRF", "WMMVF", "PGSVY", "CJREF", "NUVSF", "THST", "PIOE", "ALBHF",
			"CTPCF", "WHITF", "TIBRW", "MFCSF", "TGLVY", "RTMAF", "BYFC", "BMNM", "TRT", "ALYA", "PNRL", "VPGI", "TSRI",
			"AIXN", "EVGN", "SLGD", "BHPA", "XTEG", "TOFB", "BSEM", "QUMU", "ASRV", "EFRTF", "LND", "AMHV", "CBHMY",
			"SPRS", "TBIIF", "ALSMY", "KFS", "CAHPF", "CHPGF", "MOTUY", "CPSS", "BKEAY", "AMBO", "BIRDF", "FORK",
			"MJHI", "CIG/C", "XEBEF", "IMPHO", "CAWW", "LINC", "BMTM", "HWKE", "EQ", "AVCNF", "DELRF", "QRNNF", "CHCI",
			"PNPFF", "ETCMY", "NWARF", "VCNX", "MXCHF", "LCCTF", "ADFT", "CALZF", "FMPR", "TPDKY", "BNKL", "XYNO",
			"PSWW", "TUWLF", "DLHC", "CYRN", "ICCC", "SIF", "ABAHF", "RANKF", "BCCLF", "MTSL", "CHNR", "OSWWF", "SSNT",
			"PPSI", "NPNYY", "TEHG", "IMV", "PHGUF", "KULR", "PHCF", "SMSOF", "TLSA", "ZCOM", "CCH/WS", "RSNHF",
			"UNLRF", "TTCNF", "TPGVF", "SPPJY", "VPAHF", "TIKK", "PLBN", "GLOW", "MOGO", "BLIS", "UONEK", "TTLO",
			"PTNR", "OASMY", "MICR", "ENTX", "XIACF", "ICTSF", "EMOR", "NINK", "NWYU", "MJDLF", "QLIS", "APQT",
			"VVPR", "KZMYY", "PGNT", "BICX", "ORGS", "HBP", "OPXS", "NBGIF", "NTN", "TGEN", "CTNXF", "PECK", "FSDDF",
			"MNTMD", "ARTW", "OPGX", "OCC", "FOJCY", "PHBI", "SNBP", "CYSNF", "YIN", "APEN", "SECYF", "TRKNY", "RKFL",
			"ADVC", "ASCJF", "WSCWW", "BCII", "PUFLF", "TBTC", "BWTL", "VTSYF", "RHEpA", "LEAT", "UGRO", "GXSBY",
			"ULNV", "PRMRF", "MAORF", "CPCAF", "IHLDY", "IHT", "BYDIF", "TMED", "XJNGF", "MYOS", "OSAT", "EVK", "HOVNP",
			"XAIR", "CNCG", "TKECY", "ELMFF", "BKRIF", "ROMJF", "SLNG", "DEVV", "QUBT", "CILJF", "YAHOF", "FALC", "PIH",
			"HKTTF", "BIBLF", "RCAT", "ESCU", "BONL", "GNZUF", "CCM", "PDGRY", "ECXJ", "SSY", "NIHL", "FLMMF", "EVNVY",
			"AIRO", "MLYBY", "SUIC", "RMIAF", "RCG", "TOTZF", "CARV", "AIBRF", "AVYAW", "NWPP", "QEBR", "ERYP", "HGPI",
			"DXF", "LYL", "PAOTF", "EEIG", "IQST", "MCUJF", "SHCC", "BNSO", "COHN", "CYAN", "HLAB", "MDJH", "BNDSY",
			"ACMC", "NXNN", "AMS", "CGGYY", "PTCO", "LGYV", "PTIX" };

	public String[] StocksLessThanOne = { "CHK", "MMEX", "MINE", "FCEL", "VGID", "HMNY", "MDR", "DLOC", "MDMP", "DTSL",
			"VAPE", "DSCR", "DKGR", "MFST", "VBIV", "VGTL", "QUTR", "DPBE", "MLHC", "TRXC", "MGON", "MIKP", "ADMP",
			"SRRA", "HYSR", "VATE", "ASRT", "QTMM", "MJNA", "TEUM", "MILV", "MDCN", "AVEO", "MDGC", "TTNP", "VIBI",
			"SNSS", "AXAS", "FTR", "MEDT", "CVEO", "DRNG", "WTRH", "MJWL", "UNT", "ZN", "MHHC", "MDMN", "DMAN", "IBRC",
			"MNGG", "TRQ", "NGD", "DNRG", "ICBU", "CTST", "GLDFF", "DFODQ", "LPCN", "ASNA", "IDEX", "VIVE", "ATNM",
			"DMPI", "LODE", "DPWW", "WFTIQ", "MGTI", "DRNK", "ICNM", "UEC", "VCSY", "DLCR", "PLX", "GSM", "GSAT",
			"MGCV", "NAK", "GEMP", "DKSC", "FCUUF", "IALS", "MVIS", "MGEN", "CNAT", "DNN", "GPL", "MJTK", "SNECQ",
			"UPLC", "ONVO", "DKAM", "MLFB", "HCR", "AMPE", "HTSC", "VEND", "PVT/WS", "BLCM", "ZFGN", "LLEX", "KEG",
			"DSS", "LKSD", "IBIO", "ROYT", "AMRQQ", "VISL", "TOCA", "ICLD", "CHOOF", "EYES", "DSUS", "ZMRK", "KOPN",
			"PT", "SHLDQ", "NTRP", "OBE", "DTGI", "BAS", "JRJC", "ZIVO", "MCIG", "VGZ", "TRVN", "MJLB", "QPRC", "HDSN",
			"ENT", "VASO", "QHC", "IGC", "SPNV", "SMTA", "SMRT", "DKTS", "DLYT", "MCOA", "ICD", "TRX", "KMPH", "GNMX",
			"VDRM", "RNKLF", "REED", "LCTX", "SPHS", "NTEC", "AKG", "HTGM", "ADAP", "AAU", "ANFI", "CTIC", "CRR",
			"MCET", "VRML", "MJTV", "MCEP", "VVCIF", "VISM", "TRIL", "QUIK", "SQBG", "MCIC", "APVO", "FCSMF", "FLMZF",
			"DPSM", "RENN", "IPCIF", "WMLLF", "NXTD", "CHWRF", "VERS", "EFOI", "SRUTF", "FGP", "MNTR", "FLOOF", "AEZS",
			"AUMN", "INNT", "TGB", "XRF", "DSOX", "CHNGQ", "CHKR", "INSYQ", "HUSA", "DRSV", "TRLFF", "VIZC", "LOMLF",
			"HOS", "MARK", "AVLNF", "GLDLF", "MGNT", "NFINW", "AFH", "CLIR", "AMRWQ", "PEIX", "DPLS", "QSEP", "ELLXF",
			"VGCP", "DIRV", "CYTR", "RGLS", "NAVB", "MKRS", "DROP", "MHLD", "HX", "GYNAF", "DTST", "VIRA", "MEEC",
			"EPWCF", "MOBQ", "TISUQ", "MMMM", "DIEN", "VIVK", "DTII", "AZMTF", "NWWTF", "ADTFF", "EMAN", "VERB", "MMMB",
			"TREVF", "EURPF", "MDRM", "MICT", "HXPN", "NOBDF", "MLYF", "NSPDF", "IAHL", "FUAPF", "GLBXF", "MDTR",
			"ZSTN", "MGTC", "MFON", "NSVGF", "ZNRG", "RVLT", "ITP", "SEOVF", "CHKKF", "CDBMF", "MLWN", "DLPN",
			"PHGE/WS", "EPWMF", "REPCF", "TLGT", "PWRMF", "HYHDF", "JGLDF", "CMDRF", "DNAX", "FTEK", "HYEG", "WDRFF",
			"PNWRF", "WINMQ", "DDEJF", "DPDW", "ITMSF", "SRMMF", "AMLZF", "IBGR", "VBIO", "AQSZF", "MCTH", "TRIB",
			"GLGDF", "OSIIF", "HGTXU", "VCBD", "MEDD", "MINR", "TAOP", "DRNE", "DIGP", "TIRTZ", "OWRDF", "MMTC", "HUML",
			"ZONX", "SROYF", "AVCRF", "HZHI", "DMCD", "DVDR", "MGUY", "ICNB", "PSHIF", "MNII", "DRVD", "QNTA", "VHUB",
			"QWTR", "GTYHW", "GURE", "MHTX", "HYCTW", "ADMLF", "ISIG", "GLATF", "UAMY", "GYPHQ", "KXPLF", "DUUO",
			"VBIX", "IPATF", "AMHPF", "MGHL", "ADVZF", "HYBT", "FUGMF", "DLTI", "URAGF", "MJNE", "MCTC", "VINO",
			"PALAF", "NSRCF", "LXGTF", "HVYB", "SIREF", "GCRIF", "GGTTF", "AZKLF", "NSLPQ", "MKGP", "HTRRD", "MOCI",
			"IGGGF", "MBCI", "ZUMRF", "TRMND", "GPTRF", "PARNF", "PFMT", "MOLOF", "GPVRF", "VDPH", "CHMJF", "SRLZF",
			"HYWI", "MEDH", "MDEX", "MENC", "MBCFF", "CHPFF", "MIXX", "DSNY", "AMPYW", "ZPAS", "VCST", "DOMR", "DUOT",
			"ITMPF", "VAPR", "TIKRF", "MLCG", "ZHUD", "SNCGF", "MCCX", "GCFFF", "DNAG", "ZRVT", "LTCCF", "VIEWF",
			"DTRC", "MFMLF", "CHKIF", "DLTA", "AZNVF", "AZRMF", "SAENF", "MOJO", "SNIPF", "IPICQ", "HCCHW", "NFGRF",
			"SRSCQ", "MLPH", "VVCVF", "DLPX", "ZNAE", "CHOPF", "KOYWF", "WMLPQ", "DPFD", "MNDP", "HTTI", "VIPV",
			"LXLLF", "PAUFF", "ECRTF", "CHUFF", "DTRO", "QUAN", "QTCI", "VCON", "YLWWF", "CDIIQ", "VEST", "AMR", "NVLN",
			"NVTR", "HLTH", "AAC", "BRS", "SDT", "CLD", "FELP", "SDR", "ACETQ", "DF", "AREX", "SVVZF", "SVVZD", "SVVYF",
			"ZHDM", "HTRC", "EPWMD", "HTSF", "MBAY", "SVVTF", "MBDE", "FLDPF", "GPKMF", "MBLC", "QNXC", "MBLV", "HUGE",
			"GPKUF", "BZDLF", "DLPTF", "RNDXF", "ITKSF", "MBVA", "AMDHF", "MBVX", "HUMT", "IGESF", "CHJHF", "AMDDW",
			"FPRGF", "UDWKQ", "ZICX", "QOIL", "LXENF", "DIGI", "PNOWD", "DIGX", "MCBP", "AZLLF", "MCAP", "MCAR", "HUTN",
			"VDOMF", "BHROF", "HUWX", "CLXPF", "MCDA", "DIMN", "ECRFF", "MCGI", "DION", "MCIM", "DINO", "MCHA", "MCHN",
			"ZIPL", "QOWI", "HTPRF", "EUENF", "HVCW", "MCPI", "AMEUF", "GGPXF", "MCRT", "QPAG", "SVVDF", "ONVRF",
			"ELKMF", "MCVT", "AQQRF", "MDCE", "MDAV", "CLYXF", "MDDM", "SRLTF", "ITMCD", "MDEA", "PNRXF", "ECSIF",
			"MDFI", "MDIN", "MDGP", "HK", "ZHEXF", "FYMNF", "QPWR", "MDKM", "MDIT", "DJSP", "MDLH", "MSSNF", "ITMMF",
			"RELYQ", "GPMTF", "NSMCF", "MFMLD", "TIMCF", "SN", "MDTC", "ITMSD", "MDWK", "MDWT", "MOGIF", "DLRYF",
			"MDVX", "CHLTF", "PEYTF", "ITMZF", "NSMSF", "RRSSF", "DLRVF", "EPXYD", "ELLMF", "WHYRF", "MBAIF", "MOGLQ",
			"PWMRD", "PWMRF", "TRGCF", "SRMLF", "HWPR", "GGTHF", "MOGLF", "DKGH", "TIMGF", "HWSY", "LXGTD", "HWVI",
			"VDQSF", "GTXOD", "MJXFF", "DKMR", "IBXNF", "IGEZF", "MEIL", "AMHDD", "WHWRF", "KOREF", "MEMI", "SRKZF",
			"HTRRF", "MENB", "PALAY", "IGFFF", "NWXPF", "CZASF", "SRKRF", "MEPW", "SEEMF", "CDARF", "OARFF", "MERR",
			"QRXPF", "TMXLF", "DLAD", "DLDG", "HXPR", "DLGI", "DLII", "RRRLF", "NSLSF", "MFCO", "PEXZF", "GPMCF",
			"LFUGY", "QRSM", "URBDF", "LFUGF", "SEHKF", "PANXF", "HPIFF", "DLTZ", "HYBG", "HYBE", "HYCT", "HYDI",
			"HYDN", "HYGN", "HCCHR", "LOONF", "HYHY", "HYIG", "DHHXF", "HYII", "DMAR", "BMBPY", "QSHI", "DMEC", "TRHXY",
			"ZMDC", "HYPF", "DMDD", "CHNUF", "QSMG", "ELNOF", "ZMGD", "HYWS", "QSPW", "BMBGF", "MGFX", "MGGI", "ZHGHF",
			"MGMA", "DMTA", "LONCD", "LONCF", "MGLG", "CHPMF", "MGLO", "DMSI", "RRSXF", "HTTTF", "URANF", "MGPC",
			"UMTAF", "VALV", "NOATD", "NOATF", "GCHLF", "YHMGF", "LONKF", "RNGTF", "VAPI", "WMGIZ", "ITNRF", "DNAD",
			"GLBKF", "PNTPQ", "DNAT", "WQTEF", "AVCVD", "AVCVF", "HZNM", "ZNBR", "ZNCM", "DNDT", "SNAVF", "ADPAJ",
			"HYBOF", "ADPAS", "VDTAF", "GLBRF", "HPHWQ", "LBHRF", "ZNGY", "MHCC", "NOBGY", "CDCLF", "NOBGF", "TINNF",
			"PNTZF", "AMIUF", "DNJR", "VMNGF", "RNHEF", "MHGI", "ZNNC", "AMIQF", "PANRF", "QTXB", "PSDNF", "HYEEF",
			"DHKCF", "ZNXT", "QUES", "AVDWF", "VBTC", "VBVT", "CDDRF", "OSKIF", "BMDPY", "MOKOY", "SNEGF", "DOLV",
			"MIHL", "MIHI", "VCEX", "ELRRF", "MILC", "FLLHF", "FPVTF", "URCFD", "MIOI", "URCFF", "PSCSF", "YZCFF",
			"ELRMF", "DUROF", "VCII", "FLLCW", "FLLCR", "VCLD", "MISM", "AZRTF", "GPPRF", "VCMP", "VCPS", "ELRFF",
			"OWVID", "DPAT", "VCTL", "VCTY", "TRITF", "ZPCM", "DPER", "ADRGF", "VCYE", "TIPGF", "MJDS", "XZJBF",
			"IPDQF", "NSPXD", "UVPOF", "DPLY", "PSDMF", "FLKKF", "CDELF", "TIPNF", "DPSI", "DPRK", "SNFRF", "MJOG",
			"CHSTF", "RESCU", "ECYWF", "AIABF", "SELSF", "TRLPF", "ICABF", "ICABY", "TIRXF", "TIRXD", "GLGLF", "MJVP",
			"KTGDF", "SRSIF", "TISDZ", "MFSTD", "YUXXF", "MKAU", "AMMCF", "MBGND", "MBGNF", "PSGFF", "ITTGF", "HGTIF",
			"TRMNF", "SAAGF", "PATAF", "VIGCD", "PSGLQ", "ICAYY", "IGNGD", "KGAUF", "VEGL", "VEII", "PARDP", "GGXXF",
			"GGXXD", "MKRO", "GCLMF", "MKTY", "AIBEF", "VENV", "FCTOA", "JGFCF", "PNXPF", "FLNDF", "ELTLF", "PARLF",
			"FLNCF", "DRCR", "GLFMQ", "FUFOF", "SEKZD", "DREM", "SEKZF", "PNXLF", "PNXLD", "DRGN", "TRKWF", "DRGV",
			"RAEWF", "MFRVF", "SRRLF", "AMNCB", "CMAUF", "MOLOD", "AZTEF", "CDGXF", "MLER", "LBLTF", "ZRMG", "FLMTF",
			"RAFLF", "HYFXF", "MLLS", "DRSX", "HPMCF", "DRUS", "MLMN", "FLMNW", "FCSUF", "CMAFF", "DRWN", "EQACF",
			"ITSJF", "DRYN", "GLIID", "AMOVF", "GLIIF", "ZRZH", "QYBX", "MLTC", "NBBTF", "MLTO", "MOOIF", "SENYD",
			"PSIDD", "AICAF", "AVIJF", "CZICF", "NSUPF", "VRBRF", "PWURF", "MMBF", "AZURF", "CMBXF", "DDBXF", "DSKX",
			"MMCC", "MMEG", "AZUMF", "MBIOF", "DSOL", "GCPEF", "TROIF", "LTCPD", "CMBPF", "DSPA", "MMIO", "SRUPD",
			"AMOCF", "SNIOF", "IGPFF", "TROUF", "SWCKF", "MMNT", "LOVFF", "MMMW", "MMND", "VGLS", "AMNZF", "SRUXF",
			"RETCD", "IAIC", "TITAF", "SNGSF", "IAGX", "KTHAF", "MMTS", "VGPR", "YMAIF", "PSGTF", "MONGF", "VIGLF",
			"URGYF", "SENFF", "KTHGF", "DTEV", "MONIF", "TRNAF", "GLHRF", "AMPLQ", "MNAP", "DTHR", "DUVNF", "NSTRY",
			"MKBAF", "SNGXW", "CMCXD", "CMCXF", "MNGA", "KGBLF", "PATZF", "MNHD", "DTRM", "ELVAF", "WMNNF", "CDIXD",
			"MNMT", "SNHLF", "HLBYL", "TITXF", "CMCLF", "MNSF", "TITUF", "IBGH", "LOUIF", "IBIN", "MNTM", "MNVN",
			"NOKAF", "ADXDF", "MKEAF", "MNZO", "CMEGF", "IBSS", "MOBO", "NXEAF", "CHWTF", "IPKSF", "MODC", "MODD",
			"UEDVF", "LKKRF", "VRDSF", "GUESF", "IBXG", "IBXS", "VIAP", "RAKNF", "BZQIF", "BMKDF", "ZULU", "VICT",
			"NOKPF", "VIDA", "VICL", "VICA", "NXEOW", "VIFI", "SRWRY", "SRWRF", "ICBT", "VIGC", "MOMT", "DUTV", "MOPN",
			"CMDRD", "ICCO", "ICCT", "GUFAF", "GLLHF", "ICGL", "VINS", "NFRGF", "MBLCD", "GLLKD", "VIPK", "NSVLF",
			"ICOA", "DVAR", "MOZO", "ICNN", "ICPW", "MOPLF", "ICOX", "AMRWW", "VRCFF", "VRCFD", "AMRZF", "ICRD", "DVFI",
			"VIZG", "AIFIF", "PSJEY" };

	public String[] StocksBetweenCentsAndThree = { "OCGN", "SRNE", "VEON", "FCEL", "CBAY", "VBIV", "DFFN", "GSAT", "TNXP",
			"VSTM", "VXRT", "EROS", "HEXO", "CRNT", "AGRX", "SRRA", "PPDF", "GHSI", "ADMP", "FFHL", "AVEO", "UMRX",
			"ADXS", "TBLT", "TRXC", "TRNX", "UXIN", "GRPN", "SEEL", "CSLT", "LJPC", "PRTY", "TXMD", "MNKD", "TEUM",
			"VTGN", "ALPP", "GPOR", "SENS", "KIRK", "ACST", "CTIC", "MTNB", "ATNM", "AMRH", "OGEN", "BCRX", "AIHS",
			"ASRT", "VIVE", "XXII", "ASNA", "WKHS", "CLSD", "FNMA", "CCCL", "KSHB", "ARTH", "SESN", "DMPI", "CTST",
			"BNGO", "NBEV", "CTIB", "ZSAN", "CORV", "CFRX", "FMCC", "IDXG", "MLSS", "CVSI", "HIMX", "ACRX", "RIOT",
			"GNUS", "SNSS", "SUPV", "EVOK", "SITO", "NWBO", "RIGL", "APVO", "NSPR", "ANFI", "LPCN", "TORC", "MRNS",
			"ACOR", "SMLP", "ROYT", "TRVN", "WTRH", "GERN", "LKSD", "CVEO", "SBBP", "ATHX", "SDRL", "TANH", "AXAS",
			"CLNE", "ENZN", "DRRX", "CYCN", "HYRE", "IDEX", "PAVM", "AFMD", "TTOO", "TTSH", "APTO", "GNCA", "NBRV",
			"FLDM", "MVIS", "OPGN", "MEIP", "QBIO", "SMTA", "PRED", "ADRO", "UPLC", "GNPX", "WPRT", "ABUS", "SNDL",
			"CTDH", "CAAS", "TRIL", "ARAY", "CYDY", "RBBN", "BLPH", "OPTT", "VISL", "NTGN", "VJET", "PULM", "MBRX",
			"GNBT", "VTNR", "SCYX", "CMRX", "ONVO", "ALRN", "BLCM", "OTLK", "NEPT", "SQNS", "IWSY", "GRNF", "EYES",
			"CNAT", "ALNA", "FTFT", "TYME", "EKSO", "JRJC", "CBLI", "MGEN", "WTER", "CFMS", "ONCY", "ROAN", "KODK",
			"XBIO", "RMTI", "AVGR", "TOCA", "NTEC", "USAS", "AMPE", "INAP", "JILL", "AQMS", "CKPT", "AZRX", "FTSI",
			"TTPH", "JAGX", "UUUU", "SVRA", "DCIX", "HTBX", "CIIX", "IFMK", "BIOC", "SREV", "SUNW", "TOPS", "WATT",
			"TMDI", "PRTK", "TEDU", "INUV", "CRIS", "RCAR", "LCTX", "SGLB", "FLNT", "JMEI", "CDTX", "AVXL", "ZEST",
			"VERU", "ESTR", "NEOS", "MDCA", "SYBX", "TLGT", "AKTX", "UAVS", "BLNK", "GIGA", "CTXR", "WISA", "EXDI",
			"ACRS", "HDSN", "DSKE", "BGFV", "SGRP", "MBIO", "NVUS", "CLDX", "DCAR", "CHAP", "VLRX", "DXLG", "LKCO",
			"PHUN", "GEMP", "NXTD", "HCHC", "NYMX", "CGIP", "ALTM", "SPHS", "OTIC", "AUMN", "EARS", "SGBX", "NLST",
			"PNNX", "EMBI", "FTNW", "NIHD", "QUIK", "SPNV", "TRVG", "LIVX", "EYPT", "CPHI", "SOLO", "XELA", "SXTC",
			"CVIA", "BPMX", "CTRM", "ARPO", "SHIP", "YAYO", "VUZI", "CIFS", "BIMI", "DWSN", "CANN", "MLNT", "SNCA",
			"WHZT", "PACD", "HSDT", "STKL", "IMBI", "ADAP", "ATGN", "PTMN", "QNTA", "INNT", "ICON", "EVIO", "FPAY",
			"SOFO", "RAIL", "SYNC", "RENN", "OESX", "TUSK", "CBDS", "LPTH", "TRCH", "IDRA", "OBLN", "BBGI", "NOVN",
			"MBII", "CBAT", "PRTO", "DLPN", "LAIX", "TMRC", "PRPO", "RESN", "LEJU", "MCEP", "FTEK", "SAVA", "LWLG",
			"NWGI", "CYTR", "XSPA", "CLPS", "MARK", "ITRM", "TUES", "NMTC", "REXN", "DTII", "DLNG", "DOGZ", "SNGX",
			"LPTX", "ZFGN", "ASTC", "EAWD", "RGLS", "NGTF", "IOTC", "YRIV", "MOSY", "ARTX", "PIXY", "RCON", "SURF",
			"NLNK", "KOPN", "MPVD", "PEIX", "VTVT", "ONCS", "ATIF", "REED", "NMCI", "AYTU", "CHEK", "MRIN", "BUDZ",
			"VCBD", "REKR", "EMAN", "MRMD", "CLSN", "TROV", "NMRD", "CHCR", "BOXL", "SELB", "AEMD", "AGTC", "MHLD",
			"ARHH", "SSFT", "SAUC", "LXRP", "CLRB", "BOSC", "BKEP", "BHAT", "WAFU", "FRLI", "CODX", "FBIO", "CMXC",
			"EFOI", "KMPH", "ESEA", "EMRN", "ATOS", "KTOV", "DTEA", "NAVB", "KBSF", "AUTO", "IAHL", "PRTS", "FEDU",
			"SAEX", "AGFS", "SKYS", "CANF", "TOUR", "CYCC", "LMFA", "HTGM", "NDRA", "CLSH", "DHXM", "CIDM",
			"SINT", "PDSB", "CLSK", "CJJD", "FCSC", "VRML", "MDWD", "SINO", "CHFS", "IMMP", "AEZS", "MDCL", "SMDM",
			"EMMA", "AVCO", "INFI", "TURN", "KXIN", "RWLK", "IZEA", "ARTL", "USAU", "AREC", "SLGG", "SNES", "MOGU",
			"ACUR", "PECK", "PSTV", "UEEC", "HMMR", "PMTS", "CNET", "CYRN", "VVPR", "WSTL", "HJLI", "XCUR", "LWAY",
			"SURG", "CETX", "JAKK", "DGLY", "OCLN", "WIZP", "VOLT", "DGSE", "FRSX", "RNWK", "CWBR", "CCLP", "ECOR",
			"FORD", "CXDC", "SPEX", "HZHI", "VIVK", "ZNRG", "SFUN", "ZKIN", "BLRX", "GEVO", "BIOL", "GURE", "INBP",
			"BSQR", "ACHV", "ILAL", "TCCO", "PFIE", "ATIS", "VVUS", "CLIR", "MICR", "PCSA", "RIBT", "NCTY", "BKYI",
			"GLBS", "GIGM", "HGSH", "CYLC", "AESE", "MARA", "RMED", "MOTS", "AERG", "KITL", "ORGS", "ALPN", "ACAN",
			"AMIH", "SONM", "OIIM", "COCP", "IVOB", "CTHR", "VERB", "XELB", "HBIO", "NNDM", "SNMP", "RTIX", "MIND",
			"ROSE", "ISIG", "PIOE", "SIFY", "CHKR", "DARE", "RLBY", "DRAD", "NVCN", "VBLT", "ABIL", "SSTU", "DXYN",
			"TSSI", "CLBS", "SPCB", "BVSN", "ABTO", "ICNB", "USWS", "LONE", "NTRP", "INOD", "BABB", "HLIX", "SANW",
			"RELI", "HNRG", "FMPR", "SMRT", "ALSK", "RMBL", "IMAC", "SMMT", "DSGT", "CREX", "CTRC", "SQBG", "TENX",
			"TYHT", "IPWR", "WHLR", "STON", "BLGO", "TIXC", "SUMR", "CMOT", "GLXZ", "OPXS", "CHNR", "GTIM", "FACO",
			"CTEK", "BRLL", "IGXT", "HGLI", "TGEN", "ALYA", "DYNT", "MDLY", "NEON", "ATHE", "BNET", "CAPR", "LITB",
			"OHAI", "MTSL", "PBIO", "SALM", "UCLE", "YIPI", "BIXT", "TNLX", "GTCH", "USIO", "AACH", "XYNO", "BMMJ",
			"BWEN", "WORX", "ELGX", "AXIM", "MNDO", "GENE", "BYFC", "AEHR", "TWMC", "SRAX", "LINC", "DSWL", "RCMT",
			"FORK", "ANTE", "UTSI", "BCOM", "APEX", "SOTK", "ECSL", "MVEN", "SEDO", "APOP", "APCX", "GROW", "TCPP",
			"KGJI", "NVFY", "AIRI", "BURG", "GSUM", "NTIP", "MYOS", "MACE", "CLUB", "RAFA", "SPRT", "VODG", "STRM",
			"MICT", "VFRM", "AQUI", "JSDA", "AACG", "EVGN", "INRD", "MCTC", "NCSM", "SDPI", "AERO", "ADIL", "UOMO",
			"TAIT", "FERL", "RCAT", "IRIX", "CHRA", "PLAG", "UAMY", "BKTI", "ACTG", "IINX", "BLIN", "FNJN", "POWW",
			"HWKE", "ACFN", "LLIT", "SSKN", "STCN", "MDGS", "VPGI", "BASA", "CLWT", "FRTN", "TDNT", "THCT", "MINR",
			"TRIB", "GLOW", "RAND", "USEG", "UPPR", "SCKT", "GMBL", "LITH", "KOSS", "XDSL", "TAOP", "SEII", "HIHO",
			"DRVD", "MJNE", "ETCC", "SYPR", "ORNC", "GRAM", "CUEN", "MREO", "UDFI", "RAVE", "APEN", "MMMB",
			"PPCB", "SCOO", "QDLC", "ORGH", "NBGV", "TRPX", "QLIS", "IBAL", "BTCY", "PETZ", "DPDW", "GHMP", "ATTO",
			"AAME", "GAXY", "CBDG", "STMH", "LTFD", "SMTS", "IDSA", "STAF", "KNWN", "QALB", "EVOL", "CPAH", "AMCY",
			"NWYU", "COSM", "TKAT", "MSLP", "IVFH", "ASIN", "MKTY", "HUML", "USNU", "COFE", "IVDN", "ZDGE", "BHTG",
			"MOGO", "AMTX", "EMOR", "QUBT", "AHPI", "ALJJ", "FDBL", "ENTX", "TKCM", "SLNO", "GLYE", "BUKS", "OXBR",
			"FTMR", "FAMI", "MDJH", "PRPH", "DRNE", "CYAN", "POLA", "ECRD", "CRMZ", "DTSS", "BYSD", "ADYX", "INNV",
			"LFIN", "EXCE", "LEDS", "THST", "CURR", "TRUL", "ZCOR", "FNGR", "GRYN", "CLRO", "BSTG", "XTNT",
			"BFNH", "OWPC", "CHCI", "MCVT", "GSFI", "INLB", "CBDX", "TRXD", "QTRH", "MAGE", "NANX", "TOFB", "DLTI",
			"TBTC", "LTDH", "MFON", "USLG", "ROKK", "EDNT", "GLGI", "ALPE" };

	
	public String[] getListofStocks() {
		return ListofStocks;
	}

	public void setListofStocks(String[] listofStocks) {
		ListofStocks = listofStocks;
	}

	public String[] getStocksLessThanOne() {
		return StocksLessThanOne;
	}

	public void setStocksLessThanOne(String[] stocksLessThanOne) {
		StocksLessThanOne = stocksLessThanOne;
	}

	public String[] getStocksBetweenCentsAndThree() {
		return StocksBetweenCentsAndThree;
	}

	public void setStocksBetweenCentsAndThree(String[] stocksBetweenCentsAndThree) {
		StocksBetweenCentsAndThree = stocksBetweenCentsAndThree;
	}
	
	

}
